import { Knex } from "knex";
import pool from '../../models/pool';

const recipeIngredientData = [
    { "recipe_id": 1, "ingredient_id": 1, "quantity": 2, "unit": "stalks" },
    { "recipe_id": 1, "ingredient_id": 4, "quantity": 1, "unit": "tsp" },
    { "recipe_id": 1, "ingredient_id": 8, "quantity": 400, "unit": "ml" },
    { "recipe_id": 2, "ingredient_id": 2, "quantity": 1, "unit": "inch" },
    { "recipe_id": 2, "ingredient_id": 6, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 2, "ingredient_id": 10, "quantity": 1, "unit": "cup" },
    { "recipe_id": 3, "ingredient_id": 1, "quantity": 3, "unit": "stalks" },
    { "recipe_id": 3, "ingredient_id": 8, "quantity": 500, "unit": "ml" },
    { "recipe_id": 3, "ingredient_id": 11, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 4, "ingredient_id": 7, "quantity": 1, "unit": "tbsp" },
    { "recipe_id": 4, "ingredient_id": 13, "quantity": 300, "unit": "g" },
    { "recipe_id": 4, "ingredient_id": 8, "quantity": 200, "unit": "ml" },
    { "recipe_id": 5, "ingredient_id": 14, "quantity": 5, "unit": "cloves" },
    { "recipe_id": 5, "ingredient_id": 16, "quantity": 100, "unit": "g" },
    { "recipe_id": 5, "ingredient_id": 19, "quantity": 1, "unit": "unit" },
    { "recipe_id": 6, "ingredient_id": 3, "quantity": 4, "unit": "leaves" },
    { "recipe_id": 6, "ingredient_id": 15, "quantity": 3, "unit": "tsp" },
    { "recipe_id": 6, "ingredient_id": 21, "quantity": 1, "unit": "cup" },
    { "recipe_id": 7, "ingredient_id": 5, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 7, "ingredient_id": 17, "quantity": 1, "unit": "kg" },
    { "recipe_id": 7, "ingredient_id": 22, "quantity": 2, "unit": "cups" },
    { "recipe_id": 8, "ingredient_id": 1, "quantity": 2, "unit": "stalks" },
    { "recipe_id": 8, "ingredient_id": 6, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 8, "ingredient_id": 24, "quantity": 1, "unit": "unit" },
    { "recipe_id": 9, "ingredient_id": 8, "quantity": 250, "unit": "ml" },
    { "recipe_id": 9, "ingredient_id": 20, "quantity": 200, "unit": "g" },
    { "recipe_id": 9, "ingredient_id": 23, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 10, "ingredient_id": 12, "quantity": 1, "unit": "bunch" },
    { "recipe_id": 10, "ingredient_id": 25, "quantity": 4, "unit": "pieces" },
    { "recipe_id": 10, "ingredient_id": 27, "quantity": 2, "unit": "tsp" },
    { "recipe_id": 11, "ingredient_id": 26, "quantity": 1, "unit": "cup" },
    { "recipe_id": 11, "ingredient_id": 8, "quantity": 300, "unit": "ml" },
    { "recipe_id": 11, "ingredient_id": 15, "quantity": 4, "unit": "tsp" },
    { "recipe_id": 12, "ingredient_id": 1, "quantity": 3, "unit": "stalks" },
    { "recipe_id": 12, "ingredient_id": 5, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 12, "ingredient_id": 28, "quantity": 1, "unit": "unit" },
    { "recipe_id": 13, "ingredient_id": 8, "quantity": 400, "unit": "ml" },
    { "recipe_id": 13, "ingredient_id": 17, "quantity": 1, "unit": "kg" },
    { "recipe_id": 13, "ingredient_id": 30, "quantity": 1, "unit": "unit" },
    { "recipe_id": 14, "ingredient_id": 4, "quantity": 1, "unit": "tsp" },
    { "recipe_id": 14, "ingredient_id": 7, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 14, "ingredient_id": 29, "quantity": 2, "unit": "pieces" },
    { "recipe_id": 15, "ingredient_id": 2, "quantity": 1, "unit": "inch" },
    { "recipe_id": 15, "ingredient_id": 14, "quantity": 3, "unit": "cloves" },
    { "recipe_id": 15, "ingredient_id": 19, "quantity": 2, "unit": "units" },
    { "recipe_id": 16, "ingredient_id": 1, "quantity": 2, "unit": "stalks" },
    { "recipe_id": 16, "ingredient_id": 10, "quantity": 100, "unit": "g" },
    { "recipe_id": 16, "ingredient_id": 32, "quantity": 1, "unit": "cup" },
    { "recipe_id": 17, "ingredient_id": 5, "quantity": 1, "unit": "tbsp" },
    { "recipe_id": 17, "ingredient_id": 8, "quantity": 200, "unit": "ml" },
    { "recipe_id": 17, "ingredient_id": 22, "quantity": 1, "unit": "cup" },
    { "recipe_id": 18, "ingredient_id": 4, "quantity": 2, "unit": "tsp" },
    { "recipe_id": 18, "ingredient_id": 7, "quantity": 4, "unit": "tbsp" },
    { "recipe_id": 18, "ingredient_id": 33, "quantity": 3, "unit": "pieces" },
    { "recipe_id": 19, "ingredient_id": 6, "quantity": 1, "unit": "tbsp" },
    { "recipe_id": 19, "ingredient_id": 18, "quantity": 200, "unit": "g" },
    { "recipe_id": 19, "ingredient_id": 35, "quantity": 2, "unit": "tsp" },
    { "recipe_id": 20, "ingredient_id": 1, "quantity": 2, "unit": "stalks" },
    { "recipe_id": 20, "ingredient_id": 2, "quantity": 1, "unit": "inch" },
    { "recipe_id": 20, "ingredient_id": 37, "quantity": 1, "unit": "cup" },
    { "recipe_id": 21, "ingredient_id": 8, "quantity": 300, "unit": "ml" },
    { "recipe_id": 21, "ingredient_id": 10, "quantity": 1, "unit": "cup" },
    { "recipe_id": 21, "ingredient_id": 26, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 22, "ingredient_id": 4, "quantity": 1, "unit": "tsp" },
    { "recipe_id": 22, "ingredient_id": 6, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 22, "ingredient_id": 27, "quantity": 1, "unit": "unit" },
    { "recipe_id": 23, "ingredient_id": 1, "quantity": 2, "unit": "stalks" },
    { "recipe_id": 23, "ingredient_id": 16, "quantity": 100, "unit": "g" },
    { "recipe_id": 23, "ingredient_id": 38, "quantity": 2, "unit": "cups" },
    { "recipe_id": 24, "ingredient_id": 3, "quantity": 4, "unit": "leaves" },
    { "recipe_id": 24, "ingredient_id": 19, "quantity": 1, "unit": "unit" },
    { "recipe_id": 24, "ingredient_id": 30, "quantity": 1, "unit": "unit" },
    { "recipe_id": 25, "ingredient_id": 8, "quantity": 200, "unit": "ml" },
    { "recipe_id": 25, "ingredient_id": 22, "quantity": 2, "unit": "cups" },
    { "recipe_id": 25, "ingredient_id": 40, "quantity": 1, "unit": "unit" },
    { "recipe_id": 26, "ingredient_id": 4, "quantity": 2, "unit": "tsp" },
    { "recipe_id": 26, "ingredient_id": 12, "quantity": 1, "unit": "bunch" },
    { "recipe_id": 26, "ingredient_id": 31, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 27, "ingredient_id": 2, "quantity": 1, "unit": "inch" },
    { "recipe_id": 27, "ingredient_id": 14, "quantity": 4, "unit": "cloves" },
    { "recipe_id": 27, "ingredient_id": 32, "quantity": 1, "unit": "cup" },
    { "recipe_id": 28, "ingredient_id": 1, "quantity": 3, "unit": "stalks" },
    { "recipe_id": 28, "ingredient_id": 10, "quantity": 100, "unit": "g" },
    { "recipe_id": 28, "ingredient_id": 34, "quantity": 1, "unit": "unit" },
    { "recipe_id": 29, "ingredient_id": 5, "quantity": 2, "unit": "tbsp" },
    { "recipe_id": 29, "ingredient_id": 7, "quantity": 3, "unit": "tbsp" },
    { "recipe_id": 29, "ingredient_id": 25, "quantity": 4, "unit": "pieces" }
]

export async function seed(knex: Knex): Promise<void> {
  await pool.raw('TRUNCATE TABLE recipe_ingredient RESTART IDENTITY CASCADE');
  await knex('recipe_ingredient').insert(recipeIngredientData);
}
